In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [ ]:
df = pd.read_csv("04_pwlds_full.csv")
print(df.head())

  Password  Strength_Level
0    7hqwv               0
1     cjml               0
2     asuy               0
3    kcyth               0
4     whcq               0

In [ ]:
df.isnull().sum()

Password          6
Strength_Level    0
dtype: int64

In [ ]:
df.fillna(0,inplace=True)

In [ ]:
df.isnull().sum()

Password          0
Strength_Level    0
dtype: int64

In [ ]:
dictionary_words = [
    "password", "admin", "welcome",
    "hello", "qwerty", "letmein"
]
def extract_features(password):
    password = str(password)
    length = len(password)
    special = sum(not c.isalnum() for c in password)
    dictionary = int(any(word in password.lower() for word in dictionary_words))
    return [length, special, dictionary]
X = pd.DataFrame(
    df["Password"].apply(extract_features).tolist(),
    columns=["Length", "Special_Characters", "Dictionary_Word"]
)
y = df["Strength_Level"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("CM:",confusion_matrix(y_test,y_pred))
print("Report:",classification_report(y_test,y_pred))

Accuracy: 0.8915234690731528
CM: [[599551    107      0      0      0]
 [  3562 538278      0  59068      0]
 [     0  46052 540979  12830      0]
 [     0  36823 167012 396066      0]
 [     0      0      0      0 599897]]
Report:               precision    recall  f1-score   support

           0       0.99      1.00      1.00    599658
           1       0.87      0.90      0.88    600908
           2       0.76      0.90      0.83    599861
           3       0.85      0.66      0.74    599901
           4       1.00      1.00      1.00    599897

    accuracy                           0.89   3000225
   macro avg       0.89      0.89      0.89   3000225
weighted avg       0.89      0.89      0.89   3000225

In [ ]:
password = input("Enter password: ")
features = extract_features(password)
prediction = model.predict([features])[0]
if prediction <= 1:
  print("Password Strength: Weak")
elif prediction == 2:
    print("Password Strength: Medium")
else:
      print("Password Strength: Strong")

Enter password: qwerty
Password Strength: Weak

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(